### ISSUE TITLE
Migrate to 'prop-types' Package

### ISSUE THREAD

**Issue by skipjack** [OpenGov/react-leaflet-heatmap-layer#16]
React has deprecated internal prop types usage. The error says it all:

![image](https://cloud.githubusercontent.com/assets/8988697/25348929/e66540ba-28ed-11e7-8aed-f336ebcbf383.png)

I'd be happy to PR this fix.

**Comment by pmajkutewicz** [comment]
@skipjack PR already waiting: https://github.com/OpenGov/react-leaflet-heatmap-layer/pull/18

**Comment by skipjack** [comment]
This can be closed now with #18 merged.
