### ISSUE TITLE
Intensity of individual points not reflected. 

### ISSUE THREAD

**Issue by xinghengwang** [OpenGov/react-leaflet-heatmap-layer#26]
The intensity of each individual points doesn't seem to be reflected in the chart.  I had assumed the intensityExtractor would have an impact, but does not seems so at all. 

I pass the count as the intensity number into the HeatmapLayer as below: 

```
          <HeatmapLayer
            points={locations}
            longitudeExtractor={m => m.coordinates.lng}
            latitudeExtractor={m => m.coordinates.lat}
            intensityExtractor={m => parseFloat(m.count)}
            blur={15}
            radius={50}
            minOpacity={0.15}
          />
```
See below, I show the count by showing the marker, in Kansas, the count is 466, but it is show as the same shade of blue as the two points in Oklahoma, where the count is 142 and 13 respectively.  

![screen shot 2018-02-01 at 11 24 56 am](https://user-images.githubusercontent.com/6666687/35698725-c8c7a1b8-0742-11e8-8d92-b55bddd40f46.png)
![screen shot 2018-02-01 at 11 24 52 am](https://user-images.githubusercontent.com/6666687/35698726-c8e97752-0742-11e8-9be7-3a2b1638a3ed.png)
![screen shot 2018-02-01 at 11 24 43 am](https://user-images.githubusercontent.com/6666687/35698727-c9196d2c-0742-11e8-892c-7bc97a688204.png)

I tried to play with the max prop also, I inputed the max as the maximum of all the points of my data, or max of 3, or anything. Do not seem to have an impact on the intensity of each individual points at all. 

Can someone help me?

**Comment by spencercharest** [comment]
@xinghengwang did you ever find the solution for this? I'm wondering the same thing. Maybe I a misunderstanding `intensity`.

**Comment by xinghengwang** [comment]
unfortunately, no solution yet. :(

**Comment by Belalm** [comment]
any updates ?. I am having the same issue

**Comment by axelav** [comment]
I've found that messing with a wider range of `max` values can help with this. if the values you are returning from your `intentsityExtractor` function are larger (in the 1000s, perhaps), then a larger `max` is necessary (10 - 100). 

when your values are lower, you need a much lower (0.01 - 0.02) `max` value. I found that when I had values between 0 - 70 or so, that changing the `max` up or down even `0.01` made a huge difference.

**Comment by xinghengwang** [comment]
Thanks @axelav 
ah, that seems to be the issue. 

Took some adjustment. I just normalized everything about 50, and below worked best. 
Where maxValue is the max count of all the data set. 

```          
        <HeatmapLayer
            points={locations}
            longitudeExtractor={m => m.coordinates.lng}
            latitudeExtractor={m => m.coordinates.lat}
            intensityExtractor={m => (parseFloat(m.count) / maxValue * 50.0)}
            blur={25}
            max={0.015}
            radius={30}
          />
```
