### ISSUE TITLE
this.props.map undefined if HeatMap component is nested inside LayersControl

### ISSUE THREAD

**Issue by ruta-goomba** [OpenGov/react-leaflet-heatmap-layer#3]
The heat map renders fine if the component is directly inside the react-leaflet <Map> component, e.g.:

```
<Map center={[52.629729, -1.131592]} zoom={6}>
      <HeatmapLayer
            points={this.props.points}
            longitudeExtractor={m => m['location'][0]}
            latitudeExtractor={m => m['location'][1]}
            gradient={gradient}
            intensityExtractor={m => m['weight']}
      />
</Map>
```

However, if it is nested inside the react-leaflet <LayersControl> component (see example below), get an error 'Uncaught TypeError: Cannot read property 'getSize' of undefined'. It seems like this.props.map is not passed down to react-leaflet-heatmap-layer <HeatmapLayer> component in this case.

```
<Map center={[52.629729, -1.131592]} zoom={6}>
   <LayersControl position="topright">
       <Overlay>
           <HeatmapLayer
                points={this.props.points}
                longitudeExtractor={m => m['location'][0]}
                latitudeExtractor={m => m['location'][1]}
                gradient={gradient}
                intensityExtractor={m => m['weight']}
            />
       </Overlay>
  </LayersControl>
</Map>
```

These are the file imports for reference:

```

import React, {PropTypes} from 'react';
import { Map, TileLayer, Marker, LayersControl} from 'react-leaflet';
const { BaseLayer, Overlay } = LayersControl;
import { divIcon, point } from 'leaflet';
import HeatmapLayer from 'react-leaflet-heatmap-layer';
```

**Comment by jeremiahrhall** [comment]
Hello @ruta-goomba! It looks like that `<Overlay />` component was not part of `react-leaflet` when this was written for version `0.10.2`. In the most recent version, `0.12.1`, it looks like the API has changed such that `layerContainer` and `map` are now available via context instead of props. I have not updated to react-leaflet `0.12.1` yet but, I would welcome a PR if you would like to make this change before I get to it.

**Comment by MartinSahlen** [comment]
Hi, I just tried a search-and-replace replacing ```this.props.map``` with ```this.context.map``` and behold, it worked :) Do you want a PRQ or are you able to do this yourself @jeremiahrhall ?

**Comment by MartinSahlen** [comment]
Or, do we have do make other considerations in this case?

**Comment by MartinSahlen** [comment]
Sorry for spamming. Did some more investigations, and it seems it is not as trivial. It will work, but the heatmap will attach directly to the map and dont respect layers and hiding / showing them.
